### ISSUE TITLE
Automatic get daily arxiv papers about [Segment Anything] or [SAM]

### ISSUE THREAD

**Issue by WangRongsheng** [liliu-avril/Awesome-Segment-Anything#1]
Much work is being proposed on Segment Anything, however we are unable to keep track of them. Perhaps with the help of the arxiv api we can do this. For example:
```html
# Get [SAM] arxiv paper
https://export.arxiv.org/api/query?search_query=all:sam&start=0&max_results=30

# Get [Segment Anything] arxiv paper
https://export.arxiv.org/api/query?search_query=all:segment+anything&start=0&max_results=30
```

With python you can also automate the task of crawling these papers about segment anything or sam on a daily basis. Automation scripts demo: https://github.com/WangRongsheng/ChatGenTitle/blob/main/get_daily_llm_paper.py

I don't know if these suggestions fit this repo, but I still think it's a great thing.

**Comment by 983632847** [comment]
Great comments. We will adopt it.

**Comment by WangRongsheng** [comment]
Thank you!
