### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [liliu-avril/Awesome-Segment-Anything#2]
Thanks for meticulously maintaining this repository!

We would like to recommend our recent work on "Segment Any Point Cloud Sequences". 

We introduce **Seal**, a framework capable of leveraging 2D vision foundation models for self-supervised learning on large-scale 3D point clouds.

![Seal](https://github.com/youquanl/Segment-Any-Point-Cloud/raw/main/docs/figs/demo.gif)

- Paper: https://arxiv.org/abs/2306.09347
- Code: https://github.com/youquanl/Segment-Any-Point-Cloud
- Project Page: https://ldkong.com/Seal

Thanks a lot!

**Comment by 983632847** [comment]
Hi, we have considered your amazing paper in our list.

**Comment by ldkong1205** [comment]
Thanks for your help!
