### ISSUE TITLE
Request to add a new paper 

### ISSUE THREAD

**Issue by yangjiangeyjg** [liliu-avril/Awesome-Segment-Anything#3]
Hi, may I ask if it is possible to add a new paper related to the real robotics.

Pave the Way to Grasp Anything: Transferring Foundation Models for Universal Pick-Place Robots [Paper](https://arxiv.org/abs/2306.05716)

Thanks a lot!

**Comment by 983632847** [comment]
Hi Jiange, we have added your amazing paper to our list.

**Comment by yangjiangeyjg** [comment]
> Hi Jiange, we have added your amazing paper to our list.

Thanks!
