### ISSUE TITLE
Request for adding DefectSAM

### ISSUE THREAD

**Issue by bozhenhhu** [liliu-avril/Awesome-Segment-Anything#5]
Hi,
Could you please consider adding this project?

Segment Anything in Defect Dectection.
paper link:
https://arxiv.org/abs/2311.10245

code link:
https://github.com/bozhenhhu/DefectSAM

**Comment by 983632847** [comment]
Hi, we have added your paper to our list.

**Comment by bozhenhhu** [comment]
Thanks a lot !
