### ISSUE TITLE
Request to Update Paper Information

### ISSUE THREAD

**Issue by ymgw55** [liliu-avril/Awesome-Segment-Anything#6]
Thank you for creating such a useful repository. Our paper is already included in your list, but if possible, we would appreciate it if you could add the following information to enhance its representation:

- **Paper Title**: Zero-Shot Edge Detection With SCESAME: Spectral Clustering-Based Ensemble for Segment Anything Model Estimation
- **Conference**: WACV Workshop, 2024
- **Paper URL**: [https://openaccess.thecvf.com/content/WACV2024W/Pretrain/html/Yamagiwa_Zero-Shot_Edge_Detection_With_SCESAME_Spectral_Clustering-Based_Ensemble_for_Segment_WACVW_2024_paper.html](https://openaccess.thecvf.com/content/WACV2024W/Pretrain/html/Yamagiwa_Zero-Shot_Edge_Detection_With_SCESAME_Spectral_Clustering-Based_Ensemble_for_Segment_WACVW_2024_paper.html)
- **Code Repository**: [https://github.com/ymgw55/SCESAME](https://github.com/ymgw55/SCESAME)
- **arXiv URL**: [https://arxiv.org/abs/2308.13779](https://arxiv.org/abs/2308.13779)

**Comment by 983632847** [comment]
Hi, Yamagiwa. We have updated the information of your article in our paper list.

**Comment by ymgw55** [comment]
Thank you very much!
