### ISSUE TITLE
Code for SaLIP

### ISSUE THREAD

**Issue by aleemsidra** [liliu-avril/Awesome-Segment-Anything#7]
Hi!

Can you please add the code link to my paper: "Test-Time Adaptation with SaLIP: A Cascade of SAM and CLIP for Zero-shot Medical Image Segmentation". Here is the link to: https://github.com/aleemsidra/SaLIP .

Also can you please update the venue, it hass been accepted at "Computer Vision And Pattern Recognition Conference - Workshops 2024"

**Comment by 983632847** [comment]
All done.
